/**
 * The only place the app references logo files.
 *
 * Spec.md §6.1 sets rules that are easy to violate accidentally — never re-colour the wordmark,
 * never stretch it, never put the gradient version on a coloured background. Routing every use
 * through this component is what makes those rules hold: pick a `variant` and the correct file,
 * aspect ratio and intrinsic size come with it.
 *
 * Assets are generated by `npm run brand` from brand/aies-logo-source.svg. See
 * docs/DECISIONS.md #15.
 */

/** Content aspect ratio of the full lockup, measured from the artwork (Spec.md §6.1 records
 *  "roughly 2.6:1"; the true trimmed ratio is 2.44:1 and that is what the viewBox uses). */
const LOCKUP_RATIO = 1400 / 613;

export type LogoVariant =
  /** Full colour. Light backgrounds only — the gradient wordmark is illegible on navy. */
  | "primary"
  /** Solid white. For the navy app bar, sidebar, and PDF headers on dark. */
  | "mono-white"
  /** Solid navy. For faxed and photocopied documents. */
  | "mono-dark"
  /** The gear glyph alone. Favicon, PWA icon, collapsed sidebar — anywhere under ~120px wide,
   *  where the wordmark stops being readable. */
  | "mark";

const SOURCES: Record<LogoVariant, { src: string; ratio: number }> = {
  primary: { src: "/brand/aies-logo.svg", ratio: LOCKUP_RATIO },
  "mono-white": { src: "/brand/aies-logo-mono-white.svg", ratio: LOCKUP_RATIO },
  "mono-dark": { src: "/brand/aies-logo-mono-dark.svg", ratio: LOCKUP_RATIO },
  mark: { src: "/brand/aies-mark.svg", ratio: 1 },
};

export interface LogoProps {
  variant?: LogoVariant;
  /** Rendered height in px. Width follows from the variant's aspect ratio, so the lockup can
   *  never be stretched. */
  height?: number;
  className?: string;
  /** Set only when the logo is decorative because an adjacent element already names the company;
   *  otherwise it keeps its accessible name. */
  decorative?: boolean;
}

export function Logo({
  variant = "primary",
  height = 32,
  className,
  decorative = false,
}: LogoProps) {
  const { src, ratio } = SOURCES[variant];
  // next/image optimises rasters; these are SVGs, where it would only add a proxy hop and
  // require dangerouslyAllowSVG.
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt={decorative ? "" : "AIES Electromechanical Corporation"}
      aria-hidden={decorative || undefined}
      width={Math.round(height * ratio)}
      height={height}
      className={className}
      draggable={false}
    />
  );
}
