"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { DateCell } from "@/components/ui/cells";
import { Input, Label, Textarea } from "@/components/ui/input";
import { Card } from "@/components/ui/layout";
import { StatusBadge, type StatusTone } from "@/components/ui/status-badge";
import { toastError, toastSuccess } from "@/lib/errors";
import { trpc } from "@/lib/trpc/client";

/**
 * §2's billing plan and §4's final gate, on the order they belong to.
 *
 * ## Why these two together
 *
 * They are the same question at two ends of a job: *what will we bill, and when.* The schedule says
 * what was agreed; the gate says whether the last of it can be asked for yet. Splitting them would
 * mean checking a plan in one place and finding out it is blocked in another.
 *
 * ## What was missing
 *
 * A schedule could only be generated by a script — `generateSchedule`, `schedule`, `cancelMilestone`
 * and `finalBillingGate` all had no caller. A real order raised through the UI had no billing plan
 * at all, and §4's seven conditions were computed and never shown to anybody.
 * docs/DECISIONS.md #135.
 */

const MILESTONE_TONE: Record<string, StatusTone> = {
  pending: "draft",
  ready_to_bill: "info",
  billed: "approved",
  paid: "approved",
  cancelled: "failed",
};

const pesos = (centavos: number) =>
  `₱${(centavos / 100).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;

export function BillingPanel({ salesOrderId }: { salesOrderId: string }) {
  const utils = trpc.useUtils();
  const schedule = trpc.finance.schedule.useQuery({ salesOrderId }, { retry: false });
  const gate = trpc.finance.finalBillingGate.useQuery({ salesOrderId }, { retry: false });

  const onScheduleChanged = () => {
    void schedule.refetch();
    // `BillingReadinessPanel` is operations' own copy of the same milestone, in a sibling component
    // with its own query cache — without this, a fresh ask would not appear there until reloaded.
    void utils.finance.billingReadinessForOrder.invalidate({ salesOrderId });
  };

  // Absent rather than erroring for anybody without `finance.view`: an operations manager opening a
  // sales order should not be told a billing plan exists and is being withheld.
  if (schedule.error || schedule.isPending) return null;

  return (
    <Card className="mt-4 p-4">
      <h2 className="text-sm font-semibold">Billing</h2>

      {schedule.data === null ? (
        <NoSchedule salesOrderId={salesOrderId} onGenerated={() => void schedule.refetch()} />
      ) : (
        <>
          <p className="mt-0.5 text-xs text-text-muted">
            {schedule.data.paymentTerm?.name ?? "No term recorded"} · planned{" "}
            <DateCell value={schedule.data.generatedAt} />
          </p>

          <ul className="mt-2 space-y-2">
            {schedule.data.milestones.map((milestone) => (
              <li key={milestone.id} className="rounded-md border border-border p-2.5">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <span className="flex flex-wrap items-baseline gap-2">
                    <span className="text-sm font-medium">{milestone.label}</span>
                    <span className="text-xs text-text-muted">{milestone.pct}%</span>
                  </span>
                  <span className="flex items-center gap-2">
                    <StatusBadge tone={MILESTONE_TONE[milestone.status] ?? "draft"}>
                      {milestone.status.replace(/_/g, " ")}
                    </StatusBadge>
                    <span className="tabular text-sm font-medium">{pesos(milestone.amount)}</span>
                  </span>
                </div>

                {/*
                  Why it is or is not billable, on every row.

                  §2's stated purpose is that "finance never has to ask operations whether a project
                  is done" — which only holds if the answer is written where finance is looking.
                */}
                <p className="mt-1 text-xs text-text-muted">
                  {milestone.status === "pending" ? (
                    <>Waiting on: {milestone.triggerLabel}.</>
                  ) : (
                    <>
                      {milestone.readyReason ?? "Its trigger fired"}
                      {milestone.readyAt && (
                        <>
                          {" — "}
                          <DateCell value={milestone.readyAt} withTime />
                        </>
                      )}
                      .
                    </>
                  )}
                </p>

                {milestone.trigger === "manual" &&
                  milestone.status === "pending" &&
                  (milestone.autoRaiseOnRelease ? (
                    <ReleaseMilestone
                      milestoneId={milestone.id}
                      label={milestone.label}
                      onDone={() => void schedule.refetch()}
                    />
                  ) : (
                    <AskMilestoneReadiness
                      milestoneId={milestone.id}
                      label={milestone.label}
                      askedAt={milestone.readinessAskedAt}
                      repliedAt={milestone.readinessRepliedAt}
                      percentComplete={milestone.readinessPercentComplete}
                      estimatedDate={milestone.readinessEstimatedDate}
                      notes={milestone.readinessNotes}
                      onDone={onScheduleChanged}
                    />
                  ))}

                {milestone.trigger === "manual" && milestone.status === "invoiced" && (
                  <CustomerBillingReply
                    milestoneId={milestone.id}
                    label={milestone.label}
                    confirmedAt={milestone.customerConfirmedAt}
                    preferredDeliveryDate={milestone.customerPreferredDeliveryDate}
                    notes={milestone.customerReplyNotes}
                    onDone={() => void schedule.refetch()}
                  />
                )}

                {["pending", "ready_to_bill"].includes(milestone.status) && (
                  <CancelMilestone
                    milestoneId={milestone.id}
                    label={milestone.label}
                    onDone={() => void schedule.refetch()}
                  />
                )}
              </li>
            ))}
          </ul>

          <p className="mt-2 text-xs">
            <Link href="/finance/billing" className="underline">
              Bill what is ready
            </Link>
          </p>
        </>
      )}

      {gate.data && <FinalGate gate={gate.data} />}
    </Card>
  );
}

/**
 * An order with no billing plan.
 *
 * Said plainly rather than shown as an empty list, because the two mean different things: no plan is
 * a job nobody has decided how to bill, and that is a thing to fix rather than a state to live in.
 */
function NoSchedule({
  salesOrderId,
  onGenerated,
}: {
  salesOrderId: string;
  onGenerated: () => void;
}) {
  const generate = trpc.finance.generateSchedule.useMutation({
    onSuccess: (result) => {
      toastSuccess(`Billing plan created — ${result.milestones} milestones.`);
      onGenerated();
    },
    onError: toastError,
  });

  return (
    <>
      <p className="mt-2 text-sm">
        No billing plan. Nothing on this order can be billed until there is one — the plan is what
        decides what is asked for and when.
      </p>
      <p className="mt-1 text-xs text-text-muted">
        It is derived from the payment term on the order. If the term is missing, set it first: it
        is a commercial decision somebody negotiated, not a default.
      </p>
      <Button
        size="sm"
        className="mt-2"
        disabled={generate.isPending}
        onClick={() => generate.mutate({ salesOrderId })}
      >
        {generate.isPending ? "Planning…" : "Create the billing plan"}
      </Button>
    </>
  );
}

function CancelMilestone({
  milestoneId,
  label,
  onDone,
}: {
  milestoneId: string;
  label: string;
  onDone: () => void;
}) {
  const [open, setOpen] = useState(false);
  const [reason, setReason] = useState("");

  const cancel = trpc.finance.cancelMilestone.useMutation({
    onSuccess: () => {
      toastSuccess(`${label} cancelled.`);
      setOpen(false);
      setReason("");
      onDone();
    },
    onError: toastError,
  });

  if (!open) {
    return (
      <Button variant="ghost" size="sm" className="mt-1.5" onClick={() => setOpen(true)}>
        Cancel this milestone…
      </Button>
    );
  }

  return (
    <div className="mt-1.5 rounded-md border border-border p-2.5">
      <Label htmlFor={`ms-${milestoneId}`}>Why it will not be billed</Label>
      <Input
        id={`ms-${milestoneId}`}
        value={reason}
        placeholder="Scope removed by variation order 2; customer will not be billed for it."
        onChange={(event) => setReason(event.target.value)}
      />
      <p className="mt-1 text-xs text-text-muted">
        The plan no longer adds up to the order after this, which is correct — the reason is what
        explains the difference to anybody comparing them later.
      </p>
      <div className="mt-2 flex gap-2">
        <Button
          size="sm"
          disabled={cancel.isPending || reason.trim().length < 5}
          onClick={() => cancel.mutate({ milestoneId, reason: reason.trim() })}
        >
          Cancel it
        </Button>
        <Button variant="ghost" size="sm" onClick={() => setOpen(false)}>
          Keep it
        </Button>
      </div>
    </div>
  );
}

/**
 * docs/DECISIONS.md #184's "are we ready to bill this?" — the one act that makes a `manual` milestone
 * billable. Three of the eight payment terms have no domain event to fire on; a person judges the
 * moment and releases it by hand instead.
 */
function ReleaseMilestone({
  milestoneId,
  label,
  onDone,
}: {
  milestoneId: string;
  label: string;
  onDone: () => void;
}) {
  const release = trpc.finance.releaseMilestone.useMutation({
    onSuccess: (result) => {
      toastSuccess(
        result.statement
          ? `${label} released and statement ${result.statement.number} sent.`
          : `${label} released — it is now on finance's list to bill.`,
      );
      onDone();
    },
    onError: toastError,
  });

  return (
    <Button
      size="sm"
      variant="secondary"
      className="mt-1.5"
      disabled={release.isPending}
      onClick={() => release.mutate({ milestoneId })}
    >
      {release.isPending ? "Releasing…" : "Are we ready to bill this?"}
    </Button>
  );
}

/**
 * docs/DECISIONS.md #185 — finance's side of the "are we ready to bill this?" exchange, for a
 * `manual` milestone that is not term 3's auto-raise one. Unlike `ReleaseMilestone`, clicking this
 * does not bill anything: it asks operations, who answer through their own screen
 * (`BillingReadinessPanel`, on the same order) — finance cannot see contract amounts blocked from
 * them, but they can see whether operations answered.
 */
function AskMilestoneReadiness({
  milestoneId,
  label,
  askedAt,
  repliedAt,
  percentComplete,
  estimatedDate,
  notes,
  onDone,
}: {
  milestoneId: string;
  label: string;
  askedAt: Date | string | null;
  repliedAt: Date | string | null;
  percentComplete: string | null;
  estimatedDate: Date | string | null;
  notes: string | null;
  onDone: () => void;
}) {
  const ask = trpc.finance.askMilestoneReadiness.useMutation({
    onSuccess: () => {
      toastSuccess(`Asked operations whether ${label} is ready to bill.`);
      onDone();
    },
    onError: toastError,
  });

  // Answered since the last ask — a reply is waiting to be acted on by operations again, or the
  // most recent word is "not yet" and nothing has moved since.
  const answered = askedAt && repliedAt && new Date(repliedAt) >= new Date(askedAt);

  return (
    <div className="mt-1.5">
      {askedAt && (
        <p className="text-xs text-text-muted">
          {answered ? (
            <>
              Operations says not ready — {percentComplete}% done, expected{" "}
              <DateCell value={estimatedDate!} />.{notes && <> {notes}</>}
            </>
          ) : (
            <>
              Asked operations <DateCell value={askedAt} withTime /> — no reply yet.
            </>
          )}
        </p>
      )}
      <Button
        size="sm"
        variant="secondary"
        className="mt-1"
        disabled={ask.isPending}
        onClick={() => ask.mutate({ milestoneId })}
      >
        {ask.isPending ? "Asking…" : askedAt ? "Ask again" : "Are we ready to bill this?"}
      </Button>
    </div>
  );
}

/**
 * §14's "100% Payment on Delivery" customer reply. AIES has no customer portal, so whoever spoke to
 * the customer logs what was said here — and logging "payment is ready" is what schedules the
 * delivery, since `recordCustomerBillingReplyService` raises the delivery ticket in the same act.
 */
function CustomerBillingReply({
  milestoneId,
  label,
  confirmedAt,
  preferredDeliveryDate,
  notes,
  onDone,
}: {
  milestoneId: string;
  label: string;
  confirmedAt: Date | string | null;
  preferredDeliveryDate: Date | string | null;
  notes: string | null;
  onDone: () => void;
}) {
  const [open, setOpen] = useState(false);
  const [date, setDate] = useState("");
  const [replyNotes, setReplyNotes] = useState("");

  const reply = trpc.finance.recordCustomerBillingReply.useMutation({
    onSuccess: (result) => {
      toastSuccess(
        result.ticket
          ? `Logged — delivery ticket ${result.ticket.number} created for the preferred date.`
          : "Logged.",
      );
      setOpen(false);
      setDate("");
      setReplyNotes("");
      onDone();
    },
    onError: toastError,
  });

  if (confirmedAt) {
    return (
      <p className="mt-1.5 text-xs text-text-muted">
        Customer confirmed payment ready — preferred delivery{" "}
        <DateCell value={preferredDeliveryDate!} />.{notes && <> {notes}</>}
      </p>
    );
  }

  if (!open) {
    return (
      <Button variant="ghost" size="sm" className="mt-1.5" onClick={() => setOpen(true)}>
        Log the customer&apos;s reply…
      </Button>
    );
  }

  return (
    <div className="mt-1.5 rounded-md border border-border p-2.5">
      <p className="text-xs text-text-muted">
        {label} was billed. What did the customer say when asked about payment?
      </p>

      <Label htmlFor={`reply-date-${milestoneId}`} className="mt-2">
        Preferred delivery date
      </Label>
      <Input
        id={`reply-date-${milestoneId}`}
        type="date"
        value={date}
        onChange={(event) => setDate(event.target.value)}
      />

      <Label htmlFor={`reply-notes-${milestoneId}`} className="mt-2">
        Notes
      </Label>
      <Textarea
        id={`reply-notes-${milestoneId}`}
        rows={2}
        value={replyNotes}
        placeholder="Who was spoken to and what they said."
        onChange={(event) => setReplyNotes(event.target.value)}
      />

      <div className="mt-2 flex flex-wrap gap-2">
        <Button
          size="sm"
          disabled={reply.isPending || !date}
          onClick={() =>
            reply.mutate({
              milestoneId,
              paymentReady: true,
              preferredDeliveryDate: new Date(date),
              notes: replyNotes.trim() || null,
            })
          }
        >
          Payment is ready
        </Button>
        <Button
          variant="secondary"
          size="sm"
          disabled={reply.isPending}
          onClick={() =>
            reply.mutate({ milestoneId, paymentReady: false, notes: replyNotes.trim() || null })
          }
        >
          Not ready yet
        </Button>
        <Button variant="ghost" size="sm" onClick={() => setOpen(false)}>
          Cancel
        </Button>
      </div>
    </div>
  );
}

/**
 * §4's final billing gate — the seven conditions, and who owns each.
 *
 * ## Why every condition shows, not only the failures
 *
 * §4's list is what a customer points at when disputing a final bill. Showing only what is missing
 * would make the screen a to-do list; showing all of it makes it the evidence that the work was
 * finished, which is what somebody needs in front of them when the dispute comes.
 *
 * The owner is on every row because §4 asks for it explicitly: "waiting on operations" is a thing
 * finance can act on, and "blocked" is not.
 */
function FinalGate({
  gate,
}: {
  gate: {
    ok: boolean;
    conditions: { key: string; label: string; ok: boolean; detail?: string; owner: string }[];
  };
}) {
  if (gate.conditions.length === 0) return null;

  return (
    <div className="mt-4 border-t border-border pt-3">
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <h3 className="text-sm font-semibold">Final billing</h3>
        <StatusBadge tone={gate.ok ? "approved" : "pending"}>
          {gate.ok ? "Ready to bill in full" : "Not yet"}
        </StatusBadge>
      </div>
      <p className="mt-0.5 text-xs text-text-muted">
        {gate.ok
          ? "Everything §4 asks for is in place. The final statement can be raised."
          : "The final statement is held until these are done. The President or Vice President can override with a reason."}
      </p>

      <ul className="mt-2 space-y-1">
        {gate.conditions.map((condition) => (
          <li key={condition.key} className="flex flex-wrap items-baseline gap-2 text-xs">
            <span className={condition.ok ? "text-success" : "text-amber-700"}>
              {condition.ok ? "✓" : "•"}
            </span>
            <span className={condition.ok ? "text-text-muted" : ""}>{condition.label}</span>
            {!condition.ok && (
              <span className="text-text-muted">
                — {condition.detail ?? "not done"} · {condition.owner}
              </span>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
}
