import type { Metadata } from "next";
import { headers } from "next/headers";
import { Providers } from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "AIES Operations Platform",
  description: "Internal ERP/CRM/collaboration platform for AIES Electromechanical Corporation",
  // Generated by `npm run brand` from the gear glyph (Spec.md §6.1 — the wordmark is unreadable
  // at favicon size, so the mark is used alone).
  icons: {
    icon: [
      { url: "/brand/favicon.ico", sizes: "16x16 32x32 48x48" },
      { url: "/brand/aies-mark.svg", type: "image/svg+xml" },
    ],
    apple: "/brand/apple-touch-icon.png",
  },
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Reading the nonce here (set by middleware.ts) is what makes Next.js stamp its own
  // framework-injected scripts with it — without this, the strict production CSP's
  // 'strict-dynamic' has no matching nonce on any script tag and silently blocks all hydration.
  await headers();

  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
