import { db } from "../src/lib/db";

/**
 * Removes the residue left by *automated test runs* — not a go-live clean-up.
 *
 * `purge-test-data.ts` is the other one: it clears everything that is not the company's real work,
 * by account relationship, for the move to production. This is the smaller, more frequent job —
 * finding what the vitest fixtures left behind when a run failed part-way, or when a suite was
 * interrupted before its `afterAll` could finish.
 *
 * **Dry run by default.** Pass `--apply` to write.
 *
 * ## Why it matches on fixture patterns rather than on relationships
 *
 * The opposite of `purge-test-data.ts`'s reasoning, and deliberately so. That script argued that a
 * name pattern would break the day a real customer is called "SPO Corporation" — correct, for a
 * script that decides what is *real*. This one decides what is *synthetic*, and the fixtures use
 * markers no person would type: a `@test.local` domain, an eight-hex-character suffix, a
 * `test_checklist_` key. Those are safe precisely because they are ugly.
 *
 * Anything a person could plausibly have created is left alone. If in doubt, this script leaves it
 * and says so, because deleting somebody's work to tidy up is the one outcome worth avoiding.
 */

const APPLY = process.argv.includes("--apply");

/** Fixture markers. Every one of these is generated by a test, never typed by a person. */
const TEST_USER_DOMAIN = "@test.local";
const TEST_ACCOUNT_NAMES = ["TC Co ", "DLV Co ", "Home Co ", "SPO Co ", "TKT Co ", "MAT Co "];
const TEST_ACCOUNT_CODES = ["TC-", "DLV-", "HOME-", "SPO-", "TKT-", "MAT-"];
const TEST_CHECKLIST_KEY = "test_checklist_";
/** Actor ids the fixtures build as `<prefix>-<8 hex>`. */
const TEST_ACTOR_PREFIXES = ["chk-", "dlv-", "field-", "tkt-", "tc-", "spo-", "mat-", "home-"];

const findings: { what: string; count: number; detail?: string }[] = [];
const record = (what: string, count: number, detail?: string) => {
  findings.push({ what, count, detail });
};

async function main() {
  // ---- what is there ---------------------------------------------------------------------------

  const testUsers = await db.user.findMany({
    where: { email: { contains: TEST_USER_DOMAIN } },
    select: { id: true, email: true },
  });
  record("users on @test.local", testUsers.length);

  const accounts = await db.customerAccount.findMany({
    where: {
      OR: [
        ...TEST_ACCOUNT_NAMES.map((name) => ({ name: { startsWith: name } })),
        ...TEST_ACCOUNT_CODES.map((code) => ({ code: { startsWith: code } })),
      ],
    },
    select: { id: true, code: true, name: true },
  });
  record("fixture customer accounts", accounts.length, accounts.map((a) => a.code).join(", "));

  const templates = await db.checklistTemplate.findMany({
    where: { key: { startsWith: TEST_CHECKLIST_KEY } },
    select: { id: true, key: true },
  });
  record("fixture checklist templates", templates.length);

  const templateIds = templates.map((template) => template.id);
  const responses = await db.checklistResponse.findMany({
    where: { templateId: { in: templateIds } },
    select: { id: true },
  });
  record("their responses", responses.length);

  // Field submissions are keyed by a client UUID; the fixture ones belong to fixture actors.
  const submissions = await db.fieldSubmission.findMany({
    where: { OR: TEST_ACTOR_PREFIXES.map((prefix) => ({ userId: { startsWith: prefix } })) },
    select: { id: true },
  });
  record("field submissions from fixture actors", submissions.length);

  const outbox = await db.eventOutbox.count({
    where: { OR: TEST_ACTOR_PREFIXES.map((prefix) => ({ actorId: { startsWith: prefix } })) },
  });
  record("event outbox rows from fixture actors", outbox);

  const accountIds = accounts.map((account) => account.id);
  const tickets = await db.ticket.findMany({
    where: { accountId: { in: accountIds } },
    select: { id: true },
  });
  record("tickets on fixture accounts", tickets.length);

  const quotations = await db.quotation.findMany({
    where: { accountId: { in: accountIds } },
    select: { id: true },
  });
  record("quotations on fixture accounts", quotations.length);

  // ---- report ---------------------------------------------------------------------------------

  const total = findings.reduce((sum, finding) => sum + finding.count, 0);

  console.log(APPLY ? "APPLYING\n" : "DRY RUN — pass --apply to write\n");
  for (const finding of findings) {
    console.log(
      `  ${String(finding.count).padStart(5)}  ${finding.what}` +
        (finding.detail && finding.count > 0 ? `\n         ${finding.detail}` : ""),
    );
  }
  console.log(`\n  ${total} rows matched.`);

  if (total === 0) {
    console.log("\nNothing to remove — the fixtures cleaned up after themselves.");
    return;
  }
  if (!APPLY) {
    console.log("\nNothing written. Re-run with --apply to delete the above.");
    return;
  }

  // ---- delete, deepest first --------------------------------------------------------------------
  //
  // Same ordering discipline as purge-test-data.ts: children before parents, so a foreign key never
  // stops the run half way. A failure here is safe to re-run — nothing is deleted out of order.

  const quotationIds = quotations.map((quotation) => quotation.id);
  const ticketIds = tickets.map((ticket) => ticket.id);
  const userIds = testUsers.map((user) => user.id);

  await db.checklistResponse.deleteMany({ where: { templateId: { in: templateIds } } });
  await db.checklistTemplate.deleteMany({ where: { id: { in: templateIds } } });

  await db.fieldSubmission.deleteMany({ where: { id: { in: submissions.map((s) => s.id) } } });
  await db.eventOutbox.deleteMany({
    where: { OR: TEST_ACTOR_PREFIXES.map((prefix) => ({ actorId: { startsWith: prefix } })) },
  });

  await db.deliveryTicketFlow.deleteMany({ where: { ticketId: { in: ticketIds } } });
  await db.ticketSalesOrderLine.deleteMany({ where: { ticketId: { in: ticketIds } } });
  await db.ticket.deleteMany({ where: { id: { in: ticketIds } } });

  await db.quotationLine.deleteMany({ where: { quotationId: { in: quotationIds } } });
  await db.searchIndex.deleteMany({ where: { entityId: { in: quotationIds } } });
  await db.quotation.deleteMany({ where: { id: { in: quotationIds } } });

  await db.auditLog.deleteMany({
    where: { entityId: { in: [...ticketIds, ...quotationIds, ...accountIds, ...templateIds] } },
  });
  await db.customerAccount.deleteMany({ where: { id: { in: accountIds } } });

  await db.userRole.deleteMany({ where: { userId: { in: userIds } } });
  await db.user.deleteMany({ where: { id: { in: userIds } } });

  console.log("\nDone.");
}

main()
  .catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => {
    void db.$disconnect();
  });
